server:
  port: 8080

spring:
  application:
    name: api-gateway-hospital-poc

  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: http://localhost:8081
          predicates:
            - Path=/doctors/**
        - id: patient-service
          uri: http://localhost:8082
          predicates:
            - Path=/patients/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
